### ISSUE TITLE
Widget Still Shows Expired Alert

### ISSUE THREAD

**Issue by HonestAbe7** [justdave/nwsweatheralertswidget#56] opened 2021-12-12 21:35 UTC
I just noticed that the widget didn't update when it says the alert is expired. Still a warning there.

**Comment by justdave** [comment] 2021-12-13 02:47
Closing this as a duplicate of #29 

Basically, the app is doing something Google would prefer we not do anymore, and recent versions of Android have started enforcing it.  I've got an update in the works which does it the way Google actually wants it done, but I'm not sure how soon it'll be out (a lot of things needed to be rewritten under the hood, and I haven't had a lot of time to work on it)

See #57 for a short-term workaround I can probably get in place sooner than waiting for the rewrite to get done.

**Closed by justdave** 2021-12-13 02:47 UTC
